//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HrtzCraft.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Ui_SideBarWidth {
            get {
                return ((double)(this["Ui_SideBarWidth"]));
            }
            set {
                this["Ui_SideBarWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Ui_ConsoleInputBarHeight {
            get {
                return ((double)(this["Ui_ConsoleInputBarHeight"]));
            }
            set {
                this["Ui_ConsoleInputBarHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Ui_WindowPosTop {
            get {
                return ((double)(this["Ui_WindowPosTop"]));
            }
            set {
                this["Ui_WindowPosTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Ui_WindowPosLeft {
            get {
                return ((double)(this["Ui_WindowPosLeft"]));
            }
            set {
                this["Ui_WindowPosLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("950")]
        public double Ui_WindowWidth {
            get {
                return ((double)(this["Ui_WindowWidth"]));
            }
            set {
                this["Ui_WindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public double Ui_WindowHeight {
            get {
                return ((double)(this["Ui_WindowHeight"]));
            }
            set {
                this["Ui_WindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PlayerList_ShowBannedPlayers {
            get {
                return ((bool)(this["PlayerList_ShowBannedPlayers"]));
            }
            set {
                this["PlayerList_ShowBannedPlayers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PlayerList_ShowWhitelistedPlayers {
            get {
                return ((bool)(this["PlayerList_ShowWhitelistedPlayers"]));
            }
            set {
                this["PlayerList_ShowWhitelistedPlayers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PlayerList_ShowOpPlayers {
            get {
                return ((bool)(this["PlayerList_ShowOpPlayers"]));
            }
            set {
                this["PlayerList_ShowOpPlayers"] = value;
            }
        }
    }
}
